Implemented user registration
OlexVoit/bookshop pull request #7
Opened 2023-12-20 17:12 UTC by OlexVoit

Added RegistrationException(in CustomGlobalExceptionHandler)/AuthenticationController(endpoint - registerUser )/User(entity)/UserRepository/UserService(method register)/mapper + dto (for user).

2023-12-21 07:18 UTC, bhdnchui requested changes
Good job! Just a few points to consider.

2023-12-21 07:18 UTC, bhdnchui commented on src/main/java/mate/academy/bookshop/dto/user/UserRegistrationRequestDto.java
> +    @NotBlank(message = NOT_BE_NULL)
Do we need `@NotBlank` if we have `@Email`?

2023-12-21 07:18 UTC, bhdnchui commented on src/main/java/mate/academy/bookshop/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, HttpStatus.NOT_FOUND);
Here body is pretty equal to other handlers, please avoid code duplication

2023-12-21 07:18 UTC, bhdnchui commented on src/main/java/mate/academy/bookshop/model/Book.java
> +
```suggestion
```

2023-12-21 07:18 UTC, bhdnchui commented on src/main/java/mate/academy/bookshop/service/impl/UserServiceImpl.java
> +        user.setShippingAddress(requestDto.getShippingAddress());
Use mapper for that logic

2023-12-21 07:18 UTC, bhdnchui commented on src/main/java/mate/academy/bookshop/validation/PasswordMatchesValidator.java
> +        return user.getPassword() != null && user.getPassword().equals(user.getRepeatPassword());
Use [Objects#equals](https://www.baeldung.com/java-comparing-objects#equals-static).

2023-12-22 09:23 UTC, bhdnchui requested changes
One point to consider.

2023-12-25 20:13 UTC, bhdnchui commented on src/main/java/mate/academy/bookshop/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, HttpStatus.BAD_REQUEST);
 Body is pretty equal to handleEntityNotFoundException method body. Avoid it

2023-12-26 17:03 UTC, yevheniisynytsia requested changes
good job! let's improve code quality in the exception handler!

2023-12-26 17:03 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookshop/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(getBody(ex, HttpStatus.BAD_REQUEST), HttpStatus.BAD_REQUEST);
writing response code twice seem inconvenient
can we create a method that will get all the required parameters and return a ResponseEntity object?

2023-12-27 07:40 UTC, d1sam requested changes
Still need to improve code quality in the exception handler!

2023-12-27 07:40 UTC, d1sam commented on src/main/java/mate/academy/bookshop/exception/CustomGlobalExceptionHandler.java
> +        return body;
writing response code TWICE seem inconvenient. Please create a method that will get all the required parameters and return a ResponseEntity object?

2023-12-27 07:53 UTC, d1sam approved these changes
well done!

2023-12-27 07:53 UTC, d1sam commented on src/main/java/mate/academy/bookshop/exception/CustomGlobalExceptionHandler.java
> +                ? HttpStatus.NOT_FOUND : HttpStatus.BAD_REQUEST;
it's also not the best way, but now we can approve it.

2023-12-28 18:08 UTC, closed without merging