I wrote a bad comment. That's because I split the branches a little bit wrong.
OlexVoit/bookshop pull request #9
Opened 2023-12-27 15:49 UTC by OlexVoit

Steps:
added entity role and create table
added a table of user-roles and changed the user entity
inserted roles into the table
inserted into the users-roles table
Fixed the user repository and

2023-12-27 15:52 UTC, OlexVoit commented
I wrote a bad comment. That's because I split the branches a little bit wrong.

2023-12-27 19:51 UTC, HovorukhaBohdan approved these changes
Looks good!

2023-12-28 11:52 UTC, vovasalyha requested changes
Looks good, but see a couple of comments.

2023-12-28 11:52 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/07-insert-user-role-to-user-roles-table.yaml
> +                  value: "1"
Avoid hardcoding IDs, use valueComputed instead and select ID by email.

2023-12-28 11:52 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/07-insert-user-role-to-user-roles-table.yaml
> +                  value: "2"
Don't forget about empty lines.

2023-12-28 11:52 UTC, vovasalyha commented on src/main/resources/db/changelog/changes/04-create-user-roles-table.yaml
> +                    foreignKeyName: role_foreignKey
Try to name your constraints globally unique. Here are the conventions: https://repository.prace-ri.eu/git/help/development/database/constraint_naming_convention.md

2023-12-28 11:52 UTC, vovasalyha commented on src/main/java/mate/academy/bookshop/config/SecurityConfig.java
> +                                .requestMatchers("/api/auth/**", "/error", "/swagger-ui/**")
Add also `/v3/api-docs/**` (it's a path to generated swagger docs)

2023-12-28 13:48 UTC, d1sam requested changes
There are still some changes need to be done!

2023-12-28 13:48 UTC, d1sam commented on src/main/java/mate/academy/bookshop/controller/AuthenticationController.java
> +    }
You don't need to implement /login endpoint in this homework! remove this from pr.

2023-12-28 13:48 UTC, d1sam commented on src/main/java/mate/academy/bookshop/dto/user/UserLoginRequestDto.java
remove not related to this hw changes from pr

2023-12-28 13:48 UTC, d1sam commented on src/main/java/mate/academy/bookshop/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-28 13:48 UTC, d1sam commented on src/main/java/mate/academy/bookshop/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-28 13:48 UTC, d1sam commented on src/main/java/mate/academy/bookshop/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-28 13:48 UTC, d1sam commented on src/main/java/mate/academy/bookshop/service/impl/UserServiceImpl.java
> +        userSave.setPassword(passwordEncoder.encode(requestDto.getPassword()));
what about role of new User?

2023-12-28 13:48 UTC, d1sam commented on src/main/resources/db/changelog/changes/04-create-user-roles-table.yaml
> +      author: Oleksand voitenko
```suggestion
      author: voitenko
```
everywhere you use

2023-12-28 13:48 UTC, d1sam commented on src/main/resources/db/changelog/changes/06-insert-user.yaml
> +                  value: LA, Main Street.
```suggestion
                  value: LA, Main Street.
                  
```

2023-12-28 13:48 UTC, d1sam commented on src/main/resources/db/changelog/changes/07-insert-user-role-to-user-roles-table.yaml
> +      author: Oleksand voitenko
```suggestion
      author: voitenko
```
everywhere you use

2023-12-28 13:48 UTC, d1sam commented on src/main/resources/db/changelog/changes/07-insert-user-role-to-user-roles-table.yaml
what about `preConditions`? you should use it together with `valueComputed`!

2023-12-28 15:50 UTC, d1sam approved these changes
well done, but please look at my comments:)

2023-12-28 15:50 UTC, d1sam commented on src/main/resources/db/changelog/changes/04-create-user-roles-table.yaml
> +                    nullable: false
you have primary key, that's why nullable constraint is unnecessary
```suggestion
```

2023-12-28 15:50 UTC, d1sam commented on src/main/resources/db/changelog/changes/04-create-user-roles-table.yaml
> +                    nullable: false
you have primary key, that's why nullable constraint is unnecessary
```suggestion
```

2023-12-28 17:21 UTC, merged